[workspace]
members = ["core", "engine"]

[package]
name = "rchess"
version = "0.1.0"
authors = ["George Seabridge <georgeseabridge@gmail.com>"]
edition = "2021"

[dependencies]
core = { path = "./core" }
engine = { path = "./engine" }
clap = { version = "3.0.9", features = ["derive"] }
separator = "0.4"
