[package]
name = "rchess"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
bitintr = "0.2"
num_enum = "0.5"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "move"
harness = false

[[bench]]
name = "square"
harness = false

[[bench]]
name = "bb"
harness = false