[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
separator = "0.4"
bitflags = "1.3"
rand = "0.5.0"
log = "0.4"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "move"
harness = false
