[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
separator = "0.4"
bitflags = "1.3"
rand = "0.5.0"
log = "0.4"
num = "0.4.0"
num-derive = "0.3"
num-traits = "0.2"
unicode-segmentation = "1.9"
