[package]
name = "engine2"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
crossbeam-channel = "0.5.6"
separator = "0.4"
log = "0.4"
num = "0.4.0"
num-traits = "0.2"
num-derive = "0.3"
